/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PlanitCollection {
        "columns": number;
        "type": 'grid' | 'list';
    }
    interface PlanitContainer {
    }
}
declare global {
    interface HTMLPlanitCollectionElement extends Components.PlanitCollection, HTMLStencilElement {
    }
    var HTMLPlanitCollectionElement: {
        prototype: HTMLPlanitCollectionElement;
        new (): HTMLPlanitCollectionElement;
    };
    interface HTMLPlanitContainerElement extends Components.PlanitContainer, HTMLStencilElement {
    }
    var HTMLPlanitContainerElement: {
        prototype: HTMLPlanitContainerElement;
        new (): HTMLPlanitContainerElement;
    };
    interface HTMLElementTagNameMap {
        "planit-collection": HTMLPlanitCollectionElement;
        "planit-container": HTMLPlanitContainerElement;
    }
}
declare namespace LocalJSX {
    interface PlanitCollection {
        "columns"?: number;
        "type"?: 'grid' | 'list';
    }
    interface PlanitContainer {
    }
    interface IntrinsicElements {
        "planit-collection": PlanitCollection;
        "planit-container": PlanitContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "planit-collection": LocalJSX.PlanitCollection & JSXBase.HTMLAttributes<HTMLPlanitCollectionElement>;
            "planit-container": LocalJSX.PlanitContainer & JSXBase.HTMLAttributes<HTMLPlanitContainerElement>;
        }
    }
}
