/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SmplListItem {
    }
}
declare global {
    interface HTMLSmplListItemElement extends Components.SmplListItem, HTMLStencilElement {
    }
    var HTMLSmplListItemElement: {
        prototype: HTMLSmplListItemElement;
        new (): HTMLSmplListItemElement;
    };
    interface HTMLElementTagNameMap {
        "smpl-list-item": HTMLSmplListItemElement;
    }
}
declare namespace LocalJSX {
    interface SmplListItem {
    }
    interface IntrinsicElements {
        "smpl-list-item": SmplListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "smpl-list-item": LocalJSX.SmplListItem & JSXBase.HTMLAttributes<HTMLSmplListItemElement>;
        }
    }
}
